# Generated by Django 2.2 on 2024-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='crated_on',
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
